# .github/workflows/azure-webapps-php.yml
name: Build and deploy PHP app to Azure Web App - NT43-php-0718

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Check if composer.json exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: 'composer.json'

      - name: Run composer install if composer.json exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: composer validate --no-check-publish && composer install --prefer-dist --no-progress

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: release.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: php-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure with Service Principal
        uses: azure/login@v2
        with:
          client-id:       ${{ secrets.AZUREAPPSERVICE_CLIENTID_DFD228B721CD4776A1CF87BBE1241686 }}
          client-secret:   ${{ secrets.AZUREAPPSERVICE_CLIENTSECRET_DFD228B721CD4776A1CF87BBE1241686 }}
          tenant-id:       ${{ secrets.AZUREAPPSERVICE_TENANTID_26C9B3813737434E9B2420AE5D667F4B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DD6F4053E2104C6D9FC885389E78E67C }}

      - name: List available WebApps (for debug)
        run: |
          az account show
          az webapp list --query "[].{Name:name,RG:resourceGroup}" -o table

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name:        'NT43-php-0718'
          resource-group:  'NT'
          slot-name:       'Production'
          package:         .
